/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// There are four categories of prompts: Genres, Instruments, Moods, and Creative
export const GENRES = [
  'Acid Jazz',
  'Afrobeat',
  'Alternative Country',
  'American Folk',
  'Avant-Garde Jazz',
  'Baroque',
  'Bengal Baul',
  'Bhangra',
  'Bluegrass',
  'Blues Rock',
  'Bossa Nova',
  'Breakbeat',
  'Celtic Folk',
  'Chamber Music',
  'Chillout',
  'Chiptune',
  'Classic Rock',
  'Contemporary R&B',
  'Country',
  'Cumbia',
  'Deep House',
  'Delta Blues',
  'Digital Hardcore',
  'Disco Funk',
  'Doo Wop',
  'Drum & Bass',
  'Dubstep',
  'Electro Swing',
  'Funk Metal',
  'Gamelan',
  'Garage Rock',
  'Glitch Hop',
  'Gregorian Chant',
  'Gypsy Jazz',
  'Hard Bop Jazz',
  'Hard Rock',
  'Heavy Metal',
  'Hyperpop',
  'Indian Classical',
  'Indie Electronic',
  'Indie Folk',
  'Indie Pop',
  'Industrial Rock',
  'Irish Folk',
  'Jam Band',
  'Jamaican Dub',
  'Jazz Fusion',
  'K-Pop',
  'Klezmer',
  'Latin Jazz',
  'Lo-Fi Hip Hop',
  'Marching Band',
  'Mariachi',
  'Merengue',
  'Minimal Techno',
  'Moombahton',
  'Neo-Soul',
  'New Wave',
  'Orchestral Score',
  'Piano Ballad',
  'Polka',
  'Pop Punk',
  'Post Rock',
  'Post-Punk',
  'Progressive House',
  'Psychedelic Rock',
  'Psytrance',
  'R&B (Rhythm and Blues)',
  'Ragga Jungle',
  'Reggae',
  'Reggaeton',
  'Renaissance Music',
  'Salsa',
  'Samba',
  'Shoegaze',
  'Ska',
  'Surf Rock',
  'Synthpop',
  'Tango',
  'Techno',
  'Thrash Metal',
  'Trance',
  'Trap Music',
  'Trip Hop',
  'Vaporwave',
  'West Coast Hip Hop',
];

export const INSTRUMENTS = [
  '303 Acid Bass',
  '808 Hip Hop Beat',
  'Accordion',
  'Alto Saxophone',
  'Bagpipes',
  'Balalaika Ensemble',
  'Banjo',
  'Bass Clarinet',
  'Bassoon',
  'Bongos',
  'Boomy Bass',
  'Bouzouki',
  'Cavaquinho',
  'Cello',
  'Charango',
  'Clavichord',
  'Congo Drums',
  'Didgeridoo',
  'Dirty Synths',
  'Djembe',
  'Drumline',
  'Dulcimer',
  'Erhu',
  'Fiddle',
  'Flamenco Guitar',
  'Funk Drums',
  'Fuzz Guitar',
  'Glockenspiel',
  'Guitar',
  'Hang Drum',
  'Harmonica',
  'Harp',
  'Harpsichord',
  'Hurdy-gurdy',
  'Kalimba',
  'Koto',
  'LinnDrum',
  'Lyre',
  'Mandolin',
  'Maracas',
  'Marimba',
  'Mbira',
  'Mellotron',
  'Metallic Twang',
  'Ocarina',
  'Oud',
  'Persian Tar',
  'Pipa',
  'Precision Bass',
  'Ragtime Piano',
  'Rhodes Piano',
  'Sarod',
  'Shamisen',
  'Sitar',
  'Smooth Pianos',
  'Snappy Snare',
  'Soprano Saxophone',
  'Spacey Synths',
  'Steel Drum',
  'Synth Pads',
  'Tabla',
  'TR-909 Drum Machine',
  'Tuba',
  'Ukulele',
  'Vibraphone',
  'Viola Ensemble',
  'Warm Acoustic Guitar',
  'Woodwinds',
  'Zither',
];

export const MOODS = [
  'Acoustic Instruments',
  'Ambient',
  'Beautiful',
  'Bright Tones',
  'Chill',
  'Crunchy Distortion',
  'Danceable',
  'Dreamy',
  'Echo',
  'Eerie',
  'Emotional',
  'Ethereal Ambience',
  'Experimental',
  'Fat Beats',
  'Funky',
  'Glitchy Effects',
  'Huge Drop',
  'Live Performance',
  'Muddy Low-End',
  'Ominous Drone',
  'Psychedelic',
  'Rich Orchestration',
  'Saturated Tones',
  'Subdued Melody',
  'Sustained Chords',
  'Swirling Phasers',
  'Tight Groove',
  'Unsettling',
  'Upbeat',
  'Virtuoso',
  'Weird Noises',
];

export const CREATIVE = [
  'A Peaceful Hike',
  'A Vacuum Solo',
  'Ashes',
  'Baking a Cake',
  'Ball of Goo',
  'Brrrrr',
  'Bubbly Spring',
  'Cats Drinking Milk',
  'Cherry on Top',
  'Clones',
  'Crab Nebula',
  'Disc Golf',
  'Existential Angst',
  'Explosion',
  'Fairy Dust',
  'Feather',
  'Ice Cream Melting',
  'Icicle',
  'Juggling',
  'Jumping On Trampolines',
  'Melting',
  'Mongoose',
  'Moon Landing',
  'Nightmare',
  'Petting a Dog',
  'Quiche',
  'Rhombus',
  'Scream',
  'Sharks With Lasers',
  'Skyscrapers',
  'Sledding down a hill',
  'Swiss Cheese',
  'Taboot',
  'Taking Sail',
  'Tooth Fairy',
];
